version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./api/app:/app"
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_USER=devuser
      - DB_PASSWORD=devpassword
      - DB_NAME=databasename
    depends_on:
      - db

  # frontend-app:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:80
  #   volumes:
  #   - "./frontend:/code"

  db:
    image: postgres:13-alpine
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=databasename

volumes:
  postgres-db-data: