version: '3.9'
services:
  app:
    image: "product_manager-api:${TAG}"
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - api-volume:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_USER=devuser
      - DB_PASSWORD=devpassword
      - DB_NAME=databasename
    depends_on:
      - db

  ui:
    image: "product_manager-ui:${TAG}"
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3000:80
    volumes:
      - ui-volume:/code

  db:
    image: postgres:13-alpine
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=databasename

volumes:
  postgres-db-data:
  api-volume:
  ui-volume: