version: '3.9'
services:
  product_manager_app:
    # image: "product_manager_api:${TAG}"
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 8083:8000
    volumes:
      - product_manager_app_volume:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_USER=devuser
      - DB_PASSWORD=devpassword
      - DB_NAME=databasename
    depends_on:
      - db

  product_manager_ui:
    # image: "product_manager_ui:${TAG}"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8084:80
    volumes:
      - product_manager_ui_volume:/code

  db:
    image: postgres:13-alpine
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=databasename

volumes:
  postgres-db-data:
  product_manager_app_volume:
  product_manager_ui_volume: