# Generated by Django 3.2.4 on 2023-07-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ID',
            field=models.BigIntegerField(unique=True),
        ),
    ]
